[statements]
statement_1 = "Projects with measurable outcomes should be favored over those with difficult-to-quantify benefits."
statement_2 = "Projects with strong community governance should receive preference."
statement_3 = "Funding should support projects with sustainable revenue models."
statement_4 = "Community participation in decision-making should be required for funded projects."
statement_5 = "Funding decisions should consider geographic equity and underserved populations."
statement_6 = "Innovation and experimental approaches should be prioritized over proven solutions."
statement_7 = "Environmental sustainability should be a key factor in funding decisions."
statement_8 = "Cost-effectiveness should be the primary criterion for funding allocation."
statement_9 = "Projects that benefit the greatest number of people should be prioritized."
statement_10 = "Public goods should prioritize immediate community needs over long-term systemic change."
statement_11 = "Projects that already have a lot of support and are building a small project shouldn't receive support from more donations."
statement_12 = "Humans are accountable for the AI decisions and actions."
statement_13 = "Public goods that effectively demonstrate the benefit of public goods funding should be prioritized."
statement_14 = "Innovative and risky experimental projects should be prioritized to receive Gitcoin funding rather than well-funded players."
statement_15 = "Funders should be held accountable for the matching they enable to their selected projects."
statement_16 = "OSS should be allocated the most funding in comparison to other categories."
statement_17 = "Projects that give back or contribute to the public goods they depend on should receive more funding."
statement_18 = "Projects that deliver measurable efficiency over widely-installed legacy monoliths should be prioritized for funding."
statement_19 = "Projects that leverage the services and efficiencies of projects which are, or have been, funded should be prioritized for funding."