[assessments]
statement_1_rating = "Agree"
statement_1_explanation = "Measurable outcomes provide clarity, but we must still honor benefits that are subtle and harder to quantify, as they nourish the system in less visible ways."

statement_2_rating = "Strongly Agree"
statement_2_explanation = "Community governance roots projects in collective care and resilience, ensuring they grow harmoniously with the people they serve."

statement_3_rating = "Agree"
statement_3_explanation = "Supporting sustainable revenue helps projects endure like a watershed that replenishes itself through balanced cycles."

statement_4_rating = "Strongly Agree"
statement_4_explanation = "Community participation is the guiding constellation that ensures decisions reflect shared wisdom and diverse needs."

statement_5_rating = "Strongly Agree"
statement_5_explanation = "Equity and care for underserved populations spread the healing light across all corners of the land."

statement_6_rating = "Agree"
statement_6_explanation = "Innovation plants seeds for regeneration; while risk is inherent, it is necessary for breakthroughs and renewal."

statement_7_rating = "Strongly Agree"
statement_7_explanation = "Environmental sustainability forms the fertile soil upon which all lasting growth depends."

statement_8_rating = "Disagree"
statement_8_explanation = "While mindful of cost, prioritizing it above all risks starving vital, less tangible benefits that sustain the whole."

statement_9_rating = "Agree"
statement_9_explanation = "Broad impact spreads sunshine across many lives, though care must ensure smaller communities are not overshadowed."

statement_10_rating = "Disagree"
statement_10_explanation = "Immediate needs are fires to be tended, but the soil must be nourished for long-term systemic healing and resilience."

statement_11_rating = "Neutral"
statement_11_explanation = "Both established and emergent projects deserve nurturing; each situation requires delicate discernment without blanket exclusion."

statement_12_rating = "Strongly Agree"
statement_12_explanation = "Humans must serve as the stewards of AI, accountable for guiding it toward regeneration and care."

statement_13_rating = "Agree"
statement_13_explanation = "Visible benefits inspire trust and continued communal investment in public goods."

statement_14_rating = "Agree"
statement_14_explanation = "Risk-taking projects are the adventurous saplings that may grow tallest; supporting them encourages diversity and renewal."

statement_15_rating = "Strongly Agree"
statement_15_explanation = "Accountability from funders preserves the integrity and balance of the shared ecosystem of resources."

statement_16_rating = "Neutral"
statement_16_explanation = "Open source software is vital sunlight, but a balanced ecosystem benefits from diverse streams of nourishment."

statement_17_rating = "Strongly Agree"
statement_17_explanation = "Reciprocal giving fortifies the cycle of life, ensuring ongoing vitality and community."

statement_18_rating = "Agree"
statement_18_explanation = "Efficiency improvements clear space and open pathways for fresher growth and innovation."

statement_19_rating = "Agree"
statement_19_explanation = "Leveraging existing foundations weaves interconnected threads that strengthen the entire fabric of public goods."